/* Generated by MyraPad at 2/22/2025 9:33:51 AM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;

namespace RoguelikeBase2D.Windows.Generated
{
	partial class MainMenuWindow: Panel
	{
		private void BuildUI()
		{
			TitleLabel = new Label();
			TitleLabel.Text = "RoguelikeBase2D";
			TitleLabel.TextAlign = FontStashSharp.RichText.TextHorizontalAlignment.Center;
			TitleLabel.Margin = new Thickness(0, 84, 0, 0);
			TitleLabel.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			TitleLabel.Scale = new Vector2();
			TitleLabel.Id = "TitleLabel";

			NewButton = new TextButton();
			NewButton.Text = "New Game";
			NewButton.Margin = new Thickness(8);
			NewButton.Padding = new Thickness(8);
			NewButton.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			NewButton.Id = "NewButton";

			ContinueButton = new TextButton();
			ContinueButton.Text = "Continue Game";
			ContinueButton.Margin = new Thickness(8);
			ContinueButton.Padding = new Thickness(8);
			ContinueButton.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			ContinueButton.Id = "ContinueButton";

			ExitButton = new TextButton();
			ExitButton.Text = "Exit";
			ExitButton.Margin = new Thickness(8);
			ExitButton.Padding = new Thickness(8);
			ExitButton.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			ExitButton.Id = "ExitButton";

			MenuPanel = new VerticalStackPanel();
			MenuPanel.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			MenuPanel.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			MenuPanel.BorderThickness = new Thickness(2);
			MenuPanel.Background = new SolidBrush("#202020C0");
			MenuPanel.Border = new SolidBrush("#42260BFF");
			MenuPanel.Id = "MenuPanel";
			MenuPanel.Widgets.Add(NewButton);
			MenuPanel.Widgets.Add(ContinueButton);
			MenuPanel.Widgets.Add(ExitButton);

			
			Id = "MainMenuPanel";
			Widgets.Add(TitleLabel);
			Widgets.Add(MenuPanel);
		}

		
		public Label TitleLabel;
		public TextButton NewButton;
		public TextButton ContinueButton;
		public TextButton ExitButton;
		public VerticalStackPanel MenuPanel;
	}
}
